### ISSUE TITLE
Can't add project references

### ISSUE THREAD

**Issue by 6cUbi57z** [burtonr/csharp-kestrel-template#5]
Just been struggling with this one a bit but I think I've worked it out.

In the standard C# project (), the FunctionHandler.csproj file is referenced from the root.csproj file in the build directory. This means that any packages/references are downloaded/included as they are inherited from the child project.

However, in this repository, the root.csproj file is missing the reference (https://github.com/burtonr/csharp-kestrel-template/blob/master/template/csharp-kestrel/root.csproj). This means that it is not possible to add references.

I think I've worked out a fix so I'll do some testing and open a PR.

**Comment by burtonr** [comment]
Fixed via #6
